url: https://hinzehaley.github.io
baseurl: 

# Site settings
title: Haley Hinze
email: hinzehaley@gmail.com
description: "Android Developer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CC9933
  secondary: F1EBE4  
  greencolor: 394A38
  purplecolor: 43384A
  tancolor: A7988B

collections:
  - courses
  - skills_programming
  - skills_languages
  - skills_tools

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/hinzehaley
  - title: facebook
    url: https://www.facebook.com/haley.hinze.3
  - title: github
    url: http://github.com/hinzehaley

# Postal address (add as many lines as necessary)
address:
  - line: 385 Pearsol Loop
  - line: Cascade, ID 83611

# Build settings
markdown: kramdown
permalink: pretty