url: https://hinzehaley.github.io
baseurl: 

# Site settings
title: Haley Hinze
email: hinzehaley@gmail.com
description: "Developer for the Android mobile platform"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/hinzehaley
  - title: facebook
    url: https://www.facebook.com/haley.hinze.3
  - title: github
    url: http://github.com/hinzehaley

# Postal address (add as many lines as necessary)
address:
  - line: 300 N. College Street
  - line: Northfield, MN 55057

# Build settings
markdown: kramdown
permalink: pretty